### ISSUE TITLE
Circular dependencies problem

### ISSUE THREAD

**Issue by notexplosive** [hazzard993/love-typescript-definitions#3]
Me again! This might be a TypescriptToLua problem and not your problem but I figured I'd start here:

Scenario: I have a file `foo.ts` and another file `bar.ts` which have `export class Foo { .... }` and `export class Bar { .... }` respectively.

In `bar.ts` I can do `import { Foo } from "foo"` to use the Foo type in the Bar class, and _normally_ I can go the other way too, and give `foo.ts` an `import { Bar } from "bar"`. This is entirely legal in Typescript but it breaks on transpile because it's a circular dependency in lua.

I want Foo to know about the Bar type and vise versa. Is this possible?

Thanks!

edit: words I forgot to write

**Comment by hazzard993** [comment]
This has been fixed now! It is coming up on the next TypeScriptToLua release

**Comment by hazzard993** [comment]
This is now possible in TypeScriptToLua `0.21.0`!
