### ISSUE TITLE
Incorrect definition of love.graphics.newText

### ISSUE THREAD

**Issue by nikeinikei** [hazzard993/love-typescript-definitions#42]
This function has the following signatur:
`
function newText(font: Font, textstring?: string): Text | undefined;
`
However on the official specification (https://love2d.org/wiki/love.graphics.newText), there is no mention of it ever returning `nil`, it should always return a `Text`object

**Comment by hazzard993** [comment]
Thanks a bunch for the report!

I've fixed the signature and that change should be included with `love-typescript-definitions@0.20.1`
