### ISSUE TITLE
License

### ISSUE THREAD

**Issue by matiasah-ruydo** [hazzard993/love-typescript-definitions#44]
https://github.com/hazzard993/love-typescript-definitions/blob/66bd38ff83f7563a4bdfef73c2cdec96e2998b78/LICENSE#L3
I think you're supposed to put your name in the license file.

**Comment by hazzard993** [comment]
Thank you! :sweat_smile:

Updated it by making it similar to [TypeScriptToLua's](https://github.com/TypeScriptToLua/TypeScriptToLua/blob/master/LICENSE)
