### ISSUE TITLE
love.filesystem.write should also accept string

### ISSUE THREAD

**Issue by nikeinikei** [hazzard993/love-typescript-definitions#45]
According to the official api the function
https://love2d.org/wiki/love.filesystem.write
can accept both `string` and `Data`
however in the definitions (https://github.com/hazzard993/love-typescript-definitions/blob/master/typings/love.filesystem/functions.d.ts#L465) it only accepts `Data`

**Comment by hazzard993** [comment]
Thanks a bunch for reporting that! I've released 0.20.2 which adds this variant to _love.filesystem.write_
